services:

  portainer:

    image: portainer/portainer-ce:${PORTAINER_VERSION}

    container_name: ${PORTAINER_NAME}

    hostname: ${PORTAINER_NAME}

    restart: unless-stopped

    environment:
      TZ: ${TZ}

    ports:
      - "${PORTAINER_HTTP_PORT}:9000"
      - "${PORTAINER_HTTPS_PORT}:9443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../data/portainer:/data

    networks:
      - network

    labels:
      project: "${PROJECT_NAME}"
      stack: "infrastructure"
      service: "portainer"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:

  network:
    name: ${NETWORK_NAME}
    external: true